/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Dto
{
    public class Animation
    {
        public Metadata Metadata { get; private set; }
        public float Duration { get; private set; }
        public EntityReference[] Sources { get; private set; }
    }
}
