/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using UnityEngine;

namespace Octoio.Fey.Data.Dto
{
    public class CharacterVariantColor
    {
        public Type.CharacterVariantColor Type { get; private set; }
        public Color Color { get; private set; }
    }
}
