/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using UnityEngine;

namespace Octoio.Fey.Data.Dto
{
    public class CharacterVariant
    {
        public CharacterVariantColor[] Colors { get; private set; }
        public Vector3 Scale { get; private set; }
    }
}
