/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using UnityEngine;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public class Cursor
    {
        public Type.Cursor Type { get; private set; }
        public EntityReference IconReference { get; private set; }
        public Vector2 HotSpot { get; private set; }
    }
}
