/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using UnityEngine;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public abstract partial class Drop
    {
        public Type.Drop Type { get; private set; }
        public int Weight { get; private set; }
    }
}
