/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using UnityEngine;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public class DropEvaluation
    {
        public RequirementEvaluation Operator { get; private set; }
        public Drop[] Drops { get; private set; }
    }
}
