/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    public abstract partial class EffectTargetMechanic
    {
        public abstract T Accept<T>(IEffectTargetMechanicVisitor<T> visitor);
    }

    public partial class EffectTargetMechanicSelf : EffectTargetMechanic
    {
        public override T Accept<T>(IEffectTargetMechanicVisitor<T> visitor)
        {
            return visitor.Visit(this);
        }
    }

    public partial class EffectTargetMechanicTeam : EffectTargetMechanic
    {
        public override T Accept<T>(IEffectTargetMechanicVisitor<T> visitor)
        {
            return visitor.Visit(this);
        }
    }

    public partial class EffectTargetMechanicSelected : EffectTargetMechanic
    {
        public override T Accept<T>(IEffectTargetMechanicVisitor<T> visitor)
        {
            return visitor.Visit(this);
        }
    }

    public partial class EffectTargetMechanicCircle : EffectTargetMechanic
    {
        public override T Accept<T>(IEffectTargetMechanicVisitor<T> visitor)
        {
            return visitor.Visit(this);
        }
    }

    public partial class EffectTargetMechanicRectangle : EffectTargetMechanic
    {
        public override T Accept<T>(IEffectTargetMechanicVisitor<T> visitor)
        {
            return visitor.Visit(this);
        }
    }

}
