/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public class EntityIndex
    {
        public uint Index { get; private set; }
        public string Hash { get; private set; }
        public EntityReference Reference { get; private set; }
        public string FilePath { get; private set; }
    }
}
