/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public abstract partial class EntityDefinition
    {
        public string Owner { get; private set; }
        public Type.Entity Type { get; private set; }
        public string Key { get; private set; }
        public uint Version { get; private set; }
        public string Id { get; private set; }
    }
}
