/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using Octoio.Fey.Data.Type;
using Octoio.Fey.Data.Interface;

namespace Octoio.Fey.Data.Dto
{
    public class EntityReference : IEntityReference
    {
        public string Owner { get; private set; }
        public Entity Type { get; private set; }
        public string Key { get; private set; }
        public uint Version { get; private set; }
        public string Id { get; private set; }
    }
}
