/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using Octoio.Fey.Data.Type;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public class Equipment
    {
        public Metadata Metadata { get; private set; }
        public EquipmentCategory Category { get; private set; }
        public Data.Type.Quality Quality { get; private set; }
        public EntityReference IconReference { get; private set; }
        public StatAffix[] BaseStatAffixes { get; private set; }
        public IntRange RandomStatAffixCount { get; private set; }
        public StatAffix[] RandomStatAffixes { get; private set; }
    }
}
