/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public class FloatRange
    {
        public float Min { get; private set; }
        public float Max { get; private set; }
    }
}
