/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Dto
{
    public partial class GenericAnimationSource : AnimationSource
    {
        public Type.GenericAnimation GenericAnimationType { get; private set; }
        public int Variant { get; private set; }
    }
}
