/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using Octoio.Fey.Data.Type;

namespace Octoio.Fey.Data.Dto
{
    public class HitEffect
    {
        public Type.Hit HitType { get; private set; }
        public EffectScaling[] Scalers { get; private set; }
        public EffectTargetMechanic TargetMechanic { get; private set; }
        public EffectTarget Target { get; private set; }
        public EntityReference HitSound { get; private set; }
        public bool CanCrit { get; private set; }
        public bool CanMiss { get; private set; }
    }
}
