/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using ExplosiveLLC.RPGCharacterAnims.Core.Lookups;

namespace Octoio.Fey.Data.Dto
{
    public partial class HumanoidBlockedHitAnimationSource : AnimationSource
    {
        public BlockedHitType BlockedHitType { get; private set; }
    }
}
