/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    public interface IDropVisitor<TResult>
    {
        TResult Visit(Dto.GoldDrop goldDrop);
        TResult Visit(Dto.EquipmentDrop equipmentDrop);
        TResult Visit(Dto.WeaponDrop weaponDrop);
        TResult Visit(Dto.SkillDrop skillDrop);
    }
}
