/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    public interface IEffectTargetMechanicVisitor<TResult>
    {
        TResult Visit(Dto.EffectTargetMechanicSelf effectTargetMechanicSelf);
        TResult Visit(Dto.EffectTargetMechanicTeam effectTargetMechanicTeam);
        TResult Visit(Dto.EffectTargetMechanicSelected effectTargetMechanicSelected);
        TResult Visit(Dto.EffectTargetMechanicCircle effectTargetMechanicCircle);
        TResult Visit(Dto.EffectTargetMechanicRectangle effectTargetMechanicRectangle);
    }
}
