/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public class Image
    {
        public Type.Image Type { get; private set; }
        public string Path { get; private set; }
        public Size Size { get; private set; }
    }
}
