/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using Octoio.Fey.Data.Interface;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public partial class ImageEntityDefinition : EntityDefinition, IEntityDefinition<Image>
    {
        public Image Entity { get; private set; }
    }
}
