/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    public interface IRequirementVisitor<TResult>
    {
        TResult Visit(Dto.CharacterRequirement characterRequirement);
        TResult Visit(Dto.WeaponCategoryRequirement weaponCategoryRequirement);
    }
}
