/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    public interface ISkillActionNodeVisitor<TResult>
    {
        TResult Visit(Dto.SkillActionSequenceNode skillActionSequenceNode);
        TResult Visit(Dto.SkillActionParallelNode skillActionParallelNode);
        TResult Visit(Dto.SkillActionDelayNode skillActionDelayNode);
        TResult Visit(Dto.SkillActionAnimationNode skillActionAnimationNode);
        TResult Visit(Dto.SkillActionSoundNode skillActionSoundNode);
        TResult Visit(Dto.SkillActionHitEffectNode skillActionHitEffectNode);
        TResult Visit(Dto.SkillActionStatusEffectNode skillActionStatusEffectNode);
        TResult Visit(Dto.SkillActionSummonNode skillActionSummonNode);
        TResult Visit(Dto.SkillActionRequirementNode skillActionRequirementNode);
    }
}
