/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    public interface IStatusEffectMechanicVisitor<TResult>
    {
        TResult Visit(Dto.StatusEffectMechanicStatChange statusEffectMechanicStatChange);
        TResult Visit(Dto.StatusEffectMechanicHitOverTime statusEffectMechanicHitOverTime);
    }
}
