/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using Octoio.Fey.Data.Type;
using UnityEngine;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public partial class ProjectileHoming : Projectile
    {
        public Type.Projectile Type { get; private set; }
        public float Speed { get; private set; }
        public float RotationSpeed { get; private set; }
    }
}
