/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using Octoio.Fey.Data.Type;
using UnityEngine;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public class ProjectileSpawnPosition
    {
        public ProjectileSpawnPosition Type { get; private set; }
        public Vector3 Position { get; private set; }
        public Vector3 Offset { get; private set; }
    }
}
