/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using Octoio.Fey.Data.Type;
using UnityEngine;
using System.Collections.Generic;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public abstract partial class Projectile
    {
        public Metadata Metadata { get; private set; }
        public Type.Projectile Type { get; private set; }
        public EntityReference ModelReference { get; private set; }
        public float Lifetime { get; private set; }
        public Vector3 SpawnOffset { get; private set; }
        public int MaxHitCount { get; private set; }
        public List<ProjectileImpact> OnImpact { get; private set; }
        public List<ProjectileImpact> OnEnd { get; private set; }
    }
}
