/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using Octoio.Fey.Data.Type;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public partial class SkillActionAnimationNode : SkillActionNode
    {
        public bool ShowProgress { get; private set; }
        public float Duration { get; private set; }
        public EntityReference[] Animations { get; private set; }
    }
}
