/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using Octoio.Fey.Data.Type;
using UnityEngine;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public partial class SkillActionProjectileNode : SkillActionNode
    {
        public EntityReference Projectile { get; private set; }
        public ProjectileSpawnPosition SpawnPosition { get; private set; }
        public Vector3 Direction { get; private set; }
    }
}
