/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public class SkillEffectScaling
    {
        public float Base { get; private set; }
        public FloatRange Scaling { get; private set; }
        public Type.Stat Stat { get; private set; }
    }
}
