/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;
using Octoio.Fey.Data.Type;

namespace Octoio.Fey.Data.Dto
{
    [Serializable]
    public partial class SkillEffectTargetMechanicRectangle : SkillEffectTargetMechanic
    {
        public int HitCount { get; private set; }
        public float Width { get; private set; }
        public float Height { get; private set; }
    }
}
