/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Dto
{
    public class Sound
    {
        public EntityReference[] AudioReferences { get; private set; }
        public float SpatialBlend { get; private set; }
        public float Volume { get; private set; }
    }
}
