/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Dto
{
    public partial class StatusEffectMechanicHitOverTime : StatusEffectMechanic
    {
        public Type.Hit Hit { get; private set; }
        public float TickRate { get; private set; }
    }
}
