/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Dto
{
    public class Status
    {
        public Metadata Metadata { get; private set; }
        public StatusEffectMechanic Mechanic { get; private set; }
        public StatusStack Stack { get; private set; }
    }
}
