/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Dto
{
    public class StatusStack
    {
        public uint Size { get; private set; }
        public Type.StatusStackScalingStrategy ScalingStrategy { get; private set; }
    }
}
