/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Dto
{
    public class StatusDuration
    {
        public Type.StatusDuration Type { get; private set; }
        public float Value { get; private set; }
    }
}
