/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Dto
{
    public partial class StatusEffectMechanicStatChange : StatusEffectMechanic
    {
        public Type.Stat Stat { get; private set; }
    }
}
