/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum CharacterVariantColor : byte
    {
        Primary = 0,
        Secondary = 1,
        Tertiary = 2,
        Other = 3
    }
}
