/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum Character : byte
    {
        Adventurer = 0,
        Slime = 1,
        Boar = 2
    }
}
