/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>

using System;

namespace Octoio.Fey.Data.Type
{
    public enum Cursor : byte
    {
        General = 0,
        Target = 1,
        Attack = 2,
        Loot = 3,
        QuestBoard = 4,
        Interact = 5
    }
}
