/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum Drop : byte
    {
        Gold = 0,
        Equipment = 1,
        Weapon = 2,
        Skill = 3
    }
}
