/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum Hit : byte
    {
        Damage = 0,
        Heal = 1,
        Threat = 2,
        Mana = 3
    }
}
