/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum Image : byte
    {
        Texture = 0,
        Sprite = 1
    }
}
