/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum SkillTarget : byte
    {
        Self = 0,
        Ally = 1,
        Enemy = 2,
        Any = 3,
        Position = 4,
        None = 5
    }
}
