/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum SkillCategory : byte
    {
        None = 0,
        All = 1,
        Offense = 2,
        Defense = 3,
        Utility = 4,
        Healing = 5
    }
}
