/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum SkillEffectTargetMechanicType : byte
    {
        Self = 0,
        Team = 1,
        Selected = 2,
        Circle = 3,
        Rectangle = 4
    }
}
