/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum StatusEffectMechanic : byte
    {
        StatChange = 0,
        HitOverTime = 1
    }
}
