/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum StatusDuration : byte
    {
        Chrono = 0,
        Logical = 1,
        Room = 2,
        Dungeon = 3
    }
}
