/// <summary>
/// This file is auto-generated by the fey-data OCaml pipeline.
/// DO NOT MODIFY - Your changes will be overwritten on next generation.
/// </summary>


namespace Octoio.Fey.Data.Type
{
    public enum Target : byte
    {
        Character = 0,
        Drop = 1,
        DeadCharacter = 2,
        QuestBoard = 3,
        Portal = 4
    }
}
